const { app, BrowserWindow } = require('electron')
const fs = require('node:fs/promises')
const path = require('node:path')
const root = path.resolve(__dirname, '..')
const delay = (ms = 180) => new Promise(resolve => setTimeout(resolve, ms))
app.disableHardwareAcceleration()
app.setPath('userData', path.join(root, 'artifacts', 'tunnel-ui-' + process.pid))
setTimeout(() => { console.error('Tunnel UI verification timed out'); app.exit(1) }, 90_000).unref()
async function main() {
  await app.whenReady()
  const { createServer } = await import('vite')
  const react = (await import('@vitejs/plugin-react')).default
  const vite = await createServer({ configFile: false, root: path.join(root, 'src/renderer'), plugins: [
    { name: 'tunnel-fixture', enforce: 'pre', transform(source, id) {
      if (id.endsWith('/screenshot-init.ts')) return source.replace("Object.defineProperty(window, 'labApi'", "servers[0].jumpHost = { host: 'jump.example.test', port: 2222, username: 'relay', authType: 'privateKey' };\nObject.defineProperty(window, 'labApi'")
    } }, react()], resolve: { alias: { '@shared': path.join(root, 'src/shared') } }, server: { host: '127.0.0.1', port: 0 } })
  await vite.listen()
  const win = new BrowserWindow({ width: 1440, height: 1000, show: false, offscreen: true, webPreferences: { contextIsolation: true, sandbox: true, backgroundThrottling: false } })
  const errors = []
  win.webContents.on('console-message', event => { if (event.level === 'error') { errors.push(event.message); console.error(event.message) } })
  const run = code => win.webContents.executeJavaScript(code)
  const waitFor = async code => { for (let i = 0; i < 100; i++) { if (await run(`Boolean(${code})`)) return; await delay(100) }; throw new Error(`Timed out: ${code}`) }
  const check = async (code, label) => { if (!await run(`Boolean(${code})`)) throw new Error(label); console.log('Passed: ' + label) }
  const click = async (selector, text) => {
    await run(`(() => { const el = [...document.querySelectorAll(${JSON.stringify(selector)})].find(el => ${text ? `el.textContent.includes(${JSON.stringify(text)})` : 'true'}); if (!el) throw new Error('Missing control'); el.click() })()`)
    await delay()
  }
  const select = async (selector, value) => {
    await run(`(() => { const el = document.querySelector(${JSON.stringify(selector)}); el.value = ${JSON.stringify(value)}; el.dispatchEvent(new Event('change', { bubbles: true })) })()`)
    await delay()
  }
  const capture = async name => {
    const [width, height] = win.getSize()
    win.setSize(width + 1, height); await delay(); win.setSize(width, height); await delay(300)
    await fs.writeFile(path.join(root, 'artifacts', name), (await win.webContents.capturePage()).toPNG())
  }
  await win.loadURL(`http://127.0.0.1:${vite.httpServer.address().port}/screenshot-harness.html`)
  await waitFor('window.__captureReady')
  await click('.wb-host-actions button', 'SSH 隧道')
  await waitFor('document.querySelector(".tunnel-editor")')
  await check('document.querySelector(".tunnel-editor select").value === "demo-gpu-01"', 'server shortcut prefills server')
  await click('.tunnel-templates button', 'TensorBoard')
  await check('[...document.querySelectorAll(".tunnel-editor input[type=number]")].every(el => el.value === "6006")', 'template fills both port fields')
  await select('.tunnel-editor select', 'demo-gpu-02')
  await select('.tunnel-editor .field-wide select', 'remote')
  await check('document.querySelector(".tunnel-diagram").textContent.includes("服务器监听") && document.querySelector(".tunnel-diagram").textContent.includes("本机目标")', 'reverse forwarding updates direction and target perspective')
  await run(`(() => { const el = document.querySelector('.tunnel-editor input[maxlength="80"]'); if (!el) throw new Error('Missing name input'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(el, '反向调试'); el.dispatchEvent(new Event('input', { bubbles: true })); })()`)
  await delay()
  await click('.tunnel-editor .primary-button', '保存并启动')
  await waitFor('!document.querySelector(".tunnel-editor") && document.querySelectorAll(".tunnel-table tbody tr").length === 3')
  await check(`document.querySelector('[aria-label="停止隧道 反向调试"]') && document.querySelector('[aria-label="编辑隧道 反向调试"]').disabled`, 'saved reverse tunnel starts and cannot be edited while active')
  await check('document.querySelector(".status-tunnel-button").textContent.includes("2")', 'global active count follows start')
  await click('[aria-label="检测隧道目标 反向调试"]')
  await check('[...document.querySelectorAll(".tunnel-table tbody tr")].find(el => el.textContent.includes("反向调试")).textContent.includes("目标端口可达")', 'target probe has separate status')
  await click('[aria-label="停止隧道 反向调试"]')
  await check(`document.querySelector('[aria-label="启动隧道 反向调试"]') && !document.querySelector('[aria-label="编辑隧道 反向调试"]').disabled`, 'stop enables edit without removing config')
  await click('[aria-label="编辑隧道 反向调试"]')
  await check('document.querySelector(".tunnel-editor .field-wide select").value === "remote"', 'editing retains forwarding type')
  await click('[aria-label="关闭隧道配置"]')
  await click('[aria-label="删除隧道 反向调试"]')
  await waitFor('document.querySelector("[role=alertdialog]")')
  await click('.confirm-dialog .danger-button', '删除')
  await waitFor('document.querySelectorAll(".tunnel-table tbody tr").length === 2')
  await click('.workbench-modulebar .nav-button', '资源')
  await click('.wb-host-actions button', '连接终端')
  await waitFor('window.__labPreview.terminalConnects === 1')
  await click('[aria-label="为当前会话新建 SSH 隧道"]')
  await select('.tunnel-editor select', 'demo-gpu-01')
  await run(`(() => { const el = [...document.querySelectorAll('.tunnel-editor select')].find(el => [...el.options].some(option => option.value === 'jump')); el.value = 'jump'; el.dispatchEvent(new Event('change', { bubbles: true })); })()`)
  await delay()
  await check('document.querySelector(".tunnel-diagram").textContent.includes("跳板机") && window.__labPreview.terminalConnects === 1 && window.__labPreview.terminalCloses === 0', 'jump route is selectable and tunnel entry preserves terminal')
  await capture('tunnel-editor-dark.png')
  win.setSize(1080, 800); await delay()
  await check('document.querySelector(".tunnel-editor").getBoundingClientRect().right <= innerWidth && document.querySelector(".tunnel-editor").scrollWidth <= document.querySelector(".tunnel-editor").clientWidth', 'editor fits supported narrow window')
  await click('[aria-label="关闭隧道配置"]')
  await check('document.querySelector(".workbench-main").scrollWidth <= document.querySelector(".workbench-main").clientWidth', 'narrow table scroll stays within workbench')
  win.setSize(1440, 1000); await delay()
  await run('document.documentElement.dataset.theme = "instrument"')
  await click('.tunnel-page .workbench-page-heading button')
  await click('.tunnel-templates button', 'Jupyter')
  await capture('tunnel-editor-light.png')
  if (errors.length) throw new Error(errors.join('\n'))
  win.close(); await vite.close(); app.quit()
}
main().catch(error => { console.error(error); app.exit(1) })
